import type { Metadata } from "next";
import "../styles/globals.css";
import Footer from "@/components/footer/footer";
import { GeistSans } from "geist/font/sans";

// const geistSans = localFont({
//   src: "../public/fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 200 300 400 500 600 700 800 900",
// });
// const geistMono = localFont({
//   src: "../public/fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 200 300 400 500 600 700 800 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
